# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            ACMTVX
tagline:          'ACM TVX organization'
#description:      'Formerly known as European Interactive TV organization'
url:              http://www.acmtvx.org

author:
  name:           'ACMTVX Media Chair'
  url:            https://twitter.com/acmtvx

paginate:         5

# Custom vars
version:          0.9.0

github:
  repo:           https://github.com/organization/acmtvx
